"""empty message

Revision ID: 0a61a79042d2
Revises: e7618eb79011
Create Date: 2022-08-16 21:40:05.880100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a61a79042d2'
down_revision = 'e7618eb79011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
