"""empty message

Revision ID: 1bbea24fd315
Revises: 
Create Date: 2022-08-12 18:00:54.264498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbea24fd315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('artists', 'seekin_description')
    op.drop_column('artists', 'seeking_talent')
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('venues', 'seekin_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seekin_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venues', 'seeking_description')
    op.add_column('artists', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('artists', sa.Column('seekin_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
