"""empty message

Revision ID: 1f44e1aa01d2
Revises: 86c0ce27f57b
Create Date: 2023-04-17 00:37:33.101530

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f44e1aa01d2"
down_revision = "86c0ce27f57b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.alter_column("city", existing_type=sa.VARCHAR(length=120), nullable=False)
        batch_op.alter_column("state", existing_type=sa.VARCHAR(length=120), nullable=False)

    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.alter_column("city", existing_type=sa.VARCHAR(length=120), nullable=False)
        batch_op.alter_column("state", existing_type=sa.VARCHAR(length=120), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.alter_column("state", existing_type=sa.VARCHAR(length=120), nullable=True)
        batch_op.alter_column("city", existing_type=sa.VARCHAR(length=120), nullable=True)

    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.alter_column("state", existing_type=sa.VARCHAR(length=120), nullable=True)
        batch_op.alter_column("city", existing_type=sa.VARCHAR(length=120), nullable=True)

    # ### end Alembic commands ###
