"""empty message

Revision ID: 772c612ddfd6
Revises: b7e9b59972e5
Create Date: 2022-12-12 14:47:33.035162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772c612ddfd6'
down_revision = 'b7e9b59972e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue_genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('genre_id', 'venue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genre')
    # ### end Alembic commands ###
