"""empty message

Revision ID: 86c0ce27f57b
Revises: 443d5d613635
Create Date: 2023-04-16 23:30:52.499354

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86c0ce27f57b"
down_revision = "443d5d613635"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Show",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["Artist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["Venue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.add_column(sa.Column("website", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("seeking_venue", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("seeking_description", sa.String(length=500), nullable=True)
        )
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "genres", existing_type=sa.VARCHAR(length=120), nullable=False
        )
        batch_op.alter_column(
            "facebook_link",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=500),
            existing_nullable=True,
        )

    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("genres", sa.ARRAY(sa.String(length=120)), nullable=False)
        )
        batch_op.add_column(sa.Column("website", sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column("seeking_talent", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("seeking_description", sa.String(length=500), nullable=True)
        )
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column(
            "facebook_link",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=500),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Venue", schema=None) as batch_op:
        batch_op.alter_column(
            "facebook_link",
            existing_type=sa.String(length=500),
            type_=sa.VARCHAR(length=120),
            existing_nullable=True,
        )
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("seeking_description")
        batch_op.drop_column("seeking_talent")
        batch_op.drop_column("website")
        batch_op.drop_column("genres")

    with op.batch_alter_table("Artist", schema=None) as batch_op:
        batch_op.alter_column(
            "facebook_link",
            existing_type=sa.String(length=500),
            type_=sa.VARCHAR(length=120),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "genres", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("seeking_description")
        batch_op.drop_column("seeking_venue")
        batch_op.drop_column("website")

    op.drop_table("Show")
    # ### end Alembic commands ###
