"""empty message

Revision ID: 9e655d39b4dc
Revises: 2e507e2be329
Create Date: 2022-08-18 00:07:48.215437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e655d39b4dc'
down_revision = '2e507e2be329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(), nullable=True))
    op.drop_column('shows', 'strt_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('strt_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
