"""empty message

Revision ID: c2f3038a9e4f
Revises: 40c748a7a011
Create Date: 2022-05-29 13:17:37.300239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f3038a9e4f'
down_revision = '40c748a7a011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_items',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )

    op.add_column('Artists', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artists', sa.Column('is_venue_seeking', sa.Boolean(), nullable=False))
    op.add_column('Artists', sa.Column('venue_seeking_description', sa.String(), nullable=True))
    op.add_column('Venues', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('Venues', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venues', sa.Column('is_talent_seeking', sa.Boolean(), nullable=False))
    op.add_column('Venues', sa.Column('talent_seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venues', 'talent_seeking_description')
    op.drop_column('Venues', 'is_talent_seeking')
    op.drop_column('Venues', 'website_link')
    op.drop_column('Venues', 'address')
    op.drop_column('Artists', 'venue_seeking_description')
    op.drop_column('Artists', 'is_venue_seeking')
    op.drop_column('Artists', 'website_link')
    op.create_table('venues',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Venuess_pkey')
    )
    op.create_table('artists',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Artistss_pkey')
    )
    op.drop_table('show_items')
    # ### end Alembic commands ###
